version: '3.1'

services:
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myDatabase
        ports:
            - 3306:3306
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080
        depends_on:
            - database

    application:
        build: .
        restart: always
        ports:
            - 8081:8081