version: '3.1'

services:
  mySqlServer:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDatabase
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
    - 8082:8080
    depends_on:
    - mySqlServer

  application:
    build: .
    restart: always
    ports:
    - 8081:8081
    depends_on:
    - mySqlServer